#!/bin/bash
#PBS -M justin.ashworth@uts.edu.au
#PBS -m n
#PBS -N trinity
#PBS -o log
#PBS -e err
#PBS -S /bin/bash
#PBS -l walltime=200:00:00
#PBS -l mem=128GB
#PBS -l ncpus=48
nthread=48
mem="128G"

cd $PBS_O_WORKDIR


module load bio/Trinity-2.4.0

prog="/shared/c3/apps/Trinity-2.4.0/Trinity"
# c3 module load for latest java (setup by Leo?)
#module load devel/jdk-current

#root=srr
#root=srr.test

# give $root (root name of .left and .right read files) as -v root=[root] to qsub
outp=$root

opts="--seqType fq --CPU $nthread --max_memory $mem --trimmomatic --output $outp.trinity --normalize_reads --jaccard_clip"
files="--left `cat $root.left` --right `cat $root.right`"

$prog $opts $files 1> $outp.out 2> $outp.err

echo "done." >> $outp.out
