#!/bin/bash
#PBS -M justin.ashworth@uts.edu.au
#PBS -m n
#PBS -N blastp
#PBS -o blastp.log
#PBS -e blastp.err
#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l ncpus=4
#PBS -l mem=16GB

cd $PBS_O_WORKDIR

outfmt="6 qseqid sseqid pident length evalue"

seqloc=/shared/homes/129880/sequence
blastp -query $seqloc/$q.aa.ids.fa -db $seqloc/$s.aa.ids.fa -outfmt "$outfmt" -evalue 1e-10 -num_threads 3 > $q.$s
